<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript">
        function create(param) {
            return new Promise((resolve, reject) => {
                resolve("resolve");
            });
        };
        create().then((param) => {
            console.log("1:then,", param);
            throw "에러 발생 시킴";
        }).catch((param) => {
            console.log("2:catch,", param);
        }).then((param) => {
            console.log("3:then,", param);
        }).catch((param) => {
            consol.elog("4:catch", param);
        });

        /*
            create()에서 성공상태가 되면 resolve("resolve")호출 reject()를 작성하지 않았으므로 실패상태는 정의하지 않았다.
            create() 호출 후 성공상태가 되어 then()의 핸들러 함수 실행

            실행 : console.log("1:then,", param);

            throw문 에러 발생하여 다음 catch() 실행 throw문에 작성한 "에러 발생 시킴"이 catch() 파라미터에 설정
            실행 : console.log("2:catch,", param);

            catch()에 return 값이 없어 [[PromiseValue]] undefined 설정
            두번째 then() 실행 파라미터 값은 undefined
            
            실행  : console.log("3:then,", param);

            에러가 발생하지 않으므로 소스 종료




        */
    </script>
</body>
</html>
